name: Home Assistant MCP Server
slug: ha_mcp_clean
description: MCP server for Home Assistant
version: "1.0.0"

startup: application
boot: auto
init: false

arch:
  - amd64
  - aarch64
  - armv7
  - armhf

supervisor_api: true
homeassistant_api: true

ports:
  8000/tcp: 8000

ports_description:
  8000/tcp: MCP API server

host_network: true
