name: Home Assistant MCP Server
slug: ha_mcp_clean
description: MCP server for Home Assistant
version: "1.0.0"

startup: application
boot: auto
init: false

arch:
  - amd64
  - aarch64
  - armv7
  - armhf

options:
  ha_token: ""

schema:
  ha_token: str

environment:
  HA_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI5MDM5M2Q5ODQ2ZmU0YTM0YjA4MjI0OTE1YWRiODdhNCIsImlhdCI6MTc3MDMxMzc4NCwiZXhwIjoyMDg1NjczNzg0fQ.yn62NL4jLzkV6ky63Ai8hATYpO_Ckg8PO9iEOb3b_Wk"

ports:
  8000/tcp: 8000

ports_description:
  8000/tcp: MCP API server

host_network: true
